List<String> languages = [
  'English (US)',
  'Spanish',
  'Portuguese - Brazil',
  'Russian',
  'Indonesian',
  'Arabic',
  'French',
  'German',
  'Turkish',
  'Italian',
  'Hindi',
  'Bengali',
  'Marathi',
  'Urdu - Pakistan',
  'Gujarati',
  'Persian',
  'Dutch',
  'Polish',
  'Romanian',
  'Chinese (Traditional) Taiwan',
  'Chinese (Traditional) Hong Kong',
  'Malay',
  'Hebrew',
  'Czech',
  'Swahili',
  'Ukrainian',
  'Thai',
  'Chinese (Simplified) China',
  'Hungarian',
  'Slovak',
  'Portuguese - Portugal',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Malayalam',
  'Kannada',
  'Afrikaans',
  'Albanian',
  'Azerbaijani - latn',
  'Bulgarian',
  'Catalan',
  'Croatian',
  'Danish',
  'Estonian',
  'Filipino',
  'Finnish',
  'Greek',
  'Japanese',
  'Kazakh',
  'Korean',
  'Lao',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Norwegian',
  'Serbian - Cyrillic/Latin',
  'Slovenian',
  'Swedish',
  'Uzbek',
  'Vietnamese',
  'Irish',
];
